language: python
python:
- '3.6'
install:
- pip install -r requirements-travis.txt
script:
- python manage.py test
deploy:
  provider: heroku
  api_key:
    secure: X1FBFOMqOvdC+FyS9i8oESL43no1/ZKKyvLPsSqoCQcEDGvl87Sbr6BEb+Tq57JdfgSmEVx1z+XWK3Bo42pEMJTBuHyX5yaeZyqjrhK8nDqUQfv28Qzkutbyrypp0JLv0pkp2e7knV83AUZl+Ik4CPyiY5UWJDGjvHyPwOK/7eTvdYJtDnSrrp3GDiabmYQEXIKrcxO5A4eoRbDx3QUEwfYB7/OajbqHk6nWw4P4SJ5dltHoJc21xAjIOUow65mWlSv80X+2YXExvr1A3z1ryqAGagFS/7I+6uhznfqqlJldESPoXn5V6R/ZFoWMAavWHrL9N6D971wsSZM9mhzyrTe2MHbUnfMelFJ8E9NUmCeqQ0UbsEgDdKNjRXjaiUUS5ofq72z+veZsiCv2ijLVemAQsMMbP1i+TOX3K+8Ut92JDL4gpOYPkapIR0mTj/Y4lCEjBL3fSIVTdRarKq25aG2q0V2wtibDkC6+dviL5S72lgeEI8pDagwJBuWNBPfP/MOKUgBjvc3FS6CtgUTFLj6GvIDfDyQagOUaOljT71ArYWQH73+JHXQGIF+UCAaCaxYHwvtkFgd1xIYNzLGbc7KsDNEfrVf5E/l95239XJJiJLKKuLEEDcFuMAKI+sy5YP9tq7xE3DmNdVN0xsoYxtHQa5qi1mdND889LijRowQ=
